app/app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    path("", views.home, name="home"),
    path("track/", views.track_price, name="track_price"),
    path("item_price_graph/", views.item_price_graph, name="item_price_graph"),
    path("list_items/", views.list_items, name="list_items"),
    path("bulk_track/", views.bulk_track, name="bulk_track"),
    path(
        "get_items_by_category/",
        views.get_items_by_category,
        name="get_items_by_category",
    ),
    path("signup/", views.signup, name="signup"),
    path(
        "logout/",
        views.logout_view,
        name="logout",
    ),
    path(
        "settings/",
        views.UserSettings,
        name="settings",
    ),
]

app/crowscrape/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("app.urls")),
]

handler404 = "app.views.error_404"
handler500 = "app.views.error_500"
handler403 = "app.views.error_403"

app/app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserChangeForm
from .models import Item, UserSettings


class ItemPriceGraphForm(forms.Form):
    item_category = forms.ChoiceField(label="Select Category", required=False)
    item_id = forms.ChoiceField(label="Select Item", required=False)
    time_range = forms.ChoiceField(
        label="Select a Time Range", initial=24, required=False
    )
    TIME_CHOICES = (
        (7 * 24, "Last 7 days"),
        (5 * 24, "Last 5 days"),
        (24, "Last 24 hours"),
        (12, "Last 12 hours"),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        items = Item.objects.all()  # Replace YourModel with your actual model
        self.fields["item_id"].choices = [(item.id, item.item_name) for item in items]
        self.fields["time_range"].choices = ItemPriceGraphForm.TIME_CHOICES
        # Set field for category make sure we are only getting unique
        # categories
        self.fields["item_category"].choices = [
            (item.category, item.category) for item in items.distinct("category")
        ]


class BulkTrackForm(forms.Form):
    """BulkTrackForm is a form that allows users to enter a catagory page and track all
    items within that catagory."""

    url = forms.CharField(label="Enter URL", required=False)
    category = forms.CharField(label="Enter Category", required=False)


class SignUpForm(UserCreationForm):
    """SignupForm is a form that allows users to signup for an account."""

    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(
        max_length=254, help_text="Required. Inform a valid email address."
    )
    notification = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
            "notification",
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.notification = self.cleaned_data["notification"]
        UserSettings.objects.create(user=user, notification=user.notification)
        if commit:
            user.save()
        return user


# Add the missing import for UserUpdateForm
class UserSettingsForm(forms.ModelForm):
    """UserSettingsForm is a form that allows users to change their settings."""

    username = forms.CharField(max_length=30)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    notification = forms.BooleanField(required=False)

    class Meta:
        model = UserSettings
        fields = ("notification",)

app/app/templates/app/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <head>
        <title>{%block title %}CrowScrape{% endblock %}</title>
        </head>
    <body>
        {% if user.is_authenticated %}
        <header>
            <a href="{% url 'home' %}" class ="header-btn">Home</a>
            <a href="{% url 'track_price' %}" class ="header-btn">Track Price</a>
            <a href="{% url 'item_price_graph' %}" class ="header-btn">Item Price Graph</a>
            <a href="{% url 'list_items' %}" class ="header-btn">Item List</a>
            <a href="{% url 'bulk_track' %}" class ="header-btn">Bulk Track</a>
            <a href="{% url 'admin:index' %}" class ="header-btn">Admin</a>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class ="form-btn">Logout</button></form>
        </header>
        {% else %}
        <header>
            <a href="{% url 'home' %}" class ="header-btn">Home</a>
            <a href="{% url 'track_price' %}" class ="header-btn">Track Price</a>
            <a href="{% url 'item_price_graph' %}" class ="header-btn">Item Price Graph</a>
            <a href="{% url 'list_items' %}" class ="header-btn">Item List</a>
            <a href="{% url 'bulk_track' %}" class ="header-btn">Bulk Track</a>
            <a href="{% url 'admin:index' %}" class ="header-btn">Admin</a>
            <a href="{% url 'login' %}" class ="header-btn">Login</a>
        </header>
        {% endif %}
    </body>
<body>
    {% block content %}{% endblock %}
</body>
</html>

app/app/templates/app/bulk_track.html
<!DOCTYPE html>
{% extends "app/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h2>
    Add a Category
    </h2>
<form method="get">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Process Products">
</form>
{% endblock content %}

app/app/templates/app/home.html
{% extends "app/base.html" %}

{% block content %}
    <h1>Home</h1>
    <p> Welcome to the home page!</p>
{% endblock content %}

app/app/templates/app/item_price_graph.html
<!-- item_price_graph.html -->
<!DOCTYPE html>
{% extends "app/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<body>
    <h1>Item Price Graph</h1>

    <form method="GET">
    {% csrf_token %}
    {{ form }} <input type="submit" value="Show Graph">
    </form>
    <div>
        <!-- Display the graph using the base64 encoded data -->
        <img src="data:image/png;base64,{{ plot_data }}" alt="Price History Graph">
    </div>
    <script>
        $(document).ready(function () {
            // On change of item_category field, update the item options based on selected category
            $('#id_item_category').change(function () {
                var category = $(this).val();

                // AJAX request to fetch items based on selected category
                $.ajax({
                    url: '{% url "get_items_by_category" %}',
                    data: {
                        category: category
                    },
                    dataType: 'json',
                    success: function (data) {
                        $('#id_item_id').empty(); // Clear current options

                        // Add fetched items as options for item_id field
                        $.each(data.items, function (key, value) {
                            $('#id_item_id').append('<option value="' + key + '">' + value + '</option>');
                        });
                    }
                });
            });
        });
    </script>

</body>
{% endblock content%}

</html>

app/app/templates/app/list_items.html
{% extends "app/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content%}
    <h1>{{ title }}</h1>

<table>
    <thead>
        <tr>
            <th>Item Name</th>
            <th>Price</th>
            <th>URL</th>
            <th>Added By</th>
        </tr>
    </thead>
    <!-- To Fix price display -->
    <tbody>
        {% for item in page_obj %}
            <tr>
                <td>{{ item.item_name }}</td>
                <td>{{ item.price.price }}</td>
                <td>{{ item.item_url }}</td>
                <td>{{ item.added_by.username }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Pagination links -->
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

app/app/templates/app/signup.html
{% extends "app/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Signup!</button>
    </form>
{% endblock content%}

app/app/templates/app/success.html
<!DOCTYPE html>
{% extends "app/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1>Success</h1>
<p>{{ message }}</p>
<a href="{% url 'home' %}">Back Home</a>
{% endblock content %}

app/app/templates/app/track_price.html
<!DOCTYPE html>
<html lang="en">
    {% extends "app/base.html" %}

    {% block title %}{{ title }}{% endblock %}

    {% block content %}
<body>
    <h1>Track Price</h1>
    <form method="post" action="{% url 'track_price' %}">
        {% csrf_token %}
        <label for="url">Enter URL:</label>
        <input type="text" id="url" name="url" required><br><br>
        <label for="item_name">Item Name:</label>
        <input type="text" id="item_name" name="item_name"><br><br>
        <label for="id_category">Category:</label>
        <input type="text" id="id_category" name="category"><br><br>
        <input type="submit" value="Track Price">


    </form>
</body>
{% endblock content%}